"""End-to-end regression and core-functionality tests for ``radpair.core``.

This module covers three TODO issues:

1. **Tests for ``radpair/core.py`` — ``do_simulation``**
     - Output shape, real-valued, no NaNs.
     - Minimal (0-nucleus) and full (5-nucleus) systems.
     - Interpolation mode (``refinement > 1``).

2. **Tests for ``radpair/core.py`` — ``do_simulation_multicore``**
     - Multicore output matches single-core.
     - ``cpu_cores = 0`` (auto-detect) and ``cpu_cores = 1`` (degenerate).

3. **Create reference test spectra and end-to-end comparison tests**
     - Loads each of the 7 reference ``.npz`` files, reconstructs the
       spinsystem / experiment / simopt from stored metadata, re-runs
       ``do_simulation``, and asserts ``np.allclose`` against the stored
       intensity.

Reference spectra are regenerated by::

    uv run python tests/generate_reference_spectra.py
"""

import numpy as np
import pytest

from radpair._types import (
    Experiment,
    SimulationOptions,
    Spinsystem,
    spinsystem_field_names,
)
from radpair.core import do_simulation, do_simulation_multicore

# ---------------------------------------------------------------------------
# Helpers — load reference data and reconstruct input objects
# ---------------------------------------------------------------------------

REF_DIR = "tests/reference_data"
SPECTRA_NAMES = ["S1", "S2", "S3", "S4", "S5", "S6", "S7"]

_SPINSYSTEM_KEYS = spinsystem_field_names()


def _load_reference(
    name: str,
) -> tuple[Spinsystem, Experiment, SimulationOptions, np.ndarray]:
    """Load a reference .npz and reconstruct (spinsystem, experiment, simopt, intensity)."""
    data = np.load(f"{REF_DIR}/{name}.npz", allow_pickle=True)

    sys_kwargs: dict[str, object] = {}
    for key in _SPINSYSTEM_KEYS:
        val = data[key]
        if key in ("donor_list", "acceptor_list", "nuclei_n", "nuclei_I"):
            sys_kwargs[key] = list(val.tolist()) if val.size > 0 else []
        elif key in ("A_tensors", "A_frames"):
            sys_kwargs[key] = [np.array(v, dtype=float) for v in val]
        else:
            sys_kwargs[key] = np.array(val, dtype=float)
    spinsystem = Spinsystem(**sys_kwargs)

    experiment = Experiment(
        B_z=np.array(data["B_z"], dtype=float),
        freq_mw=float(data["freq_mw"]),
    )

    simopt = SimulationOptions(
        grid_points=int(data["grid_points"]),
        refinement=int(data["refinement"]),
        cpu_cores=int(data["cpu_cores"]),
    )

    intensity = np.array(data["intensity"], dtype=float)

    return spinsystem, experiment, simopt, intensity


# ---------------------------------------------------------------------------
# Tests for do_simulation — basic invariants
# ---------------------------------------------------------------------------


class TestDoSimulationInvariants:
    """Output-shape, dtype, and NaN checks for do_simulation."""

    def test_minimal_shape_matches_bz(
        self, minimal_spinsystem, experiment, simopt_basic
    ):
        result = do_simulation(minimal_spinsystem, experiment, simopt_basic)
        assert result.shape == experiment.B_z.shape

    def test_full_shape_matches_bz(self, full_spinsystem, experiment, simopt_basic):
        result = do_simulation(full_spinsystem, experiment, simopt_basic)
        assert result.shape == experiment.B_z.shape

    def test_minimal_real_valued(self, minimal_spinsystem, experiment, simopt_basic):
        result = do_simulation(minimal_spinsystem, experiment, simopt_basic)
        assert not np.iscomplexobj(result)

    def test_full_real_valued(self, full_spinsystem, experiment, simopt_basic):
        result = do_simulation(full_spinsystem, experiment, simopt_basic)
        assert not np.iscomplexobj(result)

    def test_minimal_no_nans(self, minimal_spinsystem, experiment, simopt_basic):
        result = do_simulation(minimal_spinsystem, experiment, simopt_basic)
        assert not np.any(np.isnan(result))

    def test_full_no_nans(self, full_spinsystem, experiment, simopt_basic):
        result = do_simulation(full_spinsystem, experiment, simopt_basic)
        assert not np.any(np.isnan(result))

    def test_minimal_no_infs(self, minimal_spinsystem, experiment, simopt_basic):
        result = do_simulation(minimal_spinsystem, experiment, simopt_basic)
        assert not np.any(np.isinf(result))

    def test_full_no_infs(self, full_spinsystem, experiment, simopt_basic):
        result = do_simulation(full_spinsystem, experiment, simopt_basic)
        assert not np.any(np.isinf(result))

    def test_interpolation_mode_shape(
        self, minimal_spinsystem, experiment, simopt_interpolation
    ):
        result = do_simulation(minimal_spinsystem, experiment, simopt_interpolation)
        assert result.shape == experiment.B_z.shape

    def test_interpolation_mode_no_nans(
        self, minimal_spinsystem, experiment, simopt_interpolation
    ):
        result = do_simulation(minimal_spinsystem, experiment, simopt_interpolation)
        assert not np.any(np.isnan(result))

    def test_interpolation_mode_changes_output(
        self, full_spinsystem, experiment, simopt_basic, simopt_interpolation
    ):
        """Interpolation should produce a (slightly) different spectrum than no-interpolation."""
        coarse = do_simulation(full_spinsystem, experiment, simopt_basic)
        fine = do_simulation(full_spinsystem, experiment, simopt_interpolation)
        assert not np.allclose(coarse, fine, rtol=1e-10, atol=1e-12)


# ---------------------------------------------------------------------------
# Tests for do_simulation_multicore
# ---------------------------------------------------------------------------


class TestDoSimulationMulticore:
    """Multicore parity and edge-case tests."""

    def test_multicore_matches_single_core(
        self, minimal_spinsystem, experiment, simopt_basic, simopt_multicore
    ):
        single = do_simulation(minimal_spinsystem, experiment, simopt_basic)
        multi = do_simulation_multicore(
            minimal_spinsystem, experiment, simopt_multicore
        )
        assert multi.shape == single.shape
        np.testing.assert_allclose(multi, single, rtol=1e-10, atol=1e-12)

    def test_multicore_auto_detect(
        self, minimal_spinsystem, experiment, simopt_auto_cores
    ):
        result = do_simulation_multicore(
            minimal_spinsystem, experiment, simopt_auto_cores
        )
        assert result.shape == experiment.B_z.shape
        assert not np.any(np.isnan(result))

    def test_multicore_single_core_degenerate(
        self, minimal_spinsystem, experiment, simopt_basic
    ):
        single = do_simulation(minimal_spinsystem, experiment, simopt_basic)
        multi = do_simulation_multicore(minimal_spinsystem, experiment, simopt_basic)
        np.testing.assert_allclose(multi, single, rtol=1e-10, atol=1e-12)

    def test_multicore_full_system_matches(
        self, full_spinsystem, experiment, simopt_basic, simopt_multicore
    ):
        single = do_simulation(full_spinsystem, experiment, simopt_basic)
        multi = do_simulation_multicore(full_spinsystem, experiment, simopt_multicore)
        np.testing.assert_allclose(multi, single, rtol=1e-10, atol=1e-12)


# ---------------------------------------------------------------------------
# End-to-end regression tests against reference spectra
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("name", SPECTRA_NAMES)
def test_reference_spectrum(name: str) -> None:
    """Re-run do_simulation for a reference case and compare to stored intensity."""
    spinsystem, experiment, simopt, expected = _load_reference(name)
    result = do_simulation(spinsystem, experiment, simopt)
    assert result.shape == expected.shape
    np.testing.assert_allclose(result, expected, rtol=1e-10, atol=1e-12)


def test_reference_spectra_have_nonzero_variance() -> None:
    """All reference spectra should have meaningful structure (not flat lines)."""
    for name in SPECTRA_NAMES:
        _, _, _, intensity = _load_reference(name)
        assert np.std(intensity) > 0, f"{name} has zero variance"
        assert np.any(intensity != 0), f"{name} is all zeros"


def test_reference_spectra_have_negative_and_positive() -> None:
    """Spin-correlated radical pairs produce both absorptive and emissive lines."""
    for name in SPECTRA_NAMES:
        _, _, _, intensity = _load_reference(name)
        assert np.any(intensity > 0), f"{name} has no positive intensities"
        assert np.any(intensity < 0), f"{name} has no negative intensities"


def test_swap_pair_s3_s4_have_similar_sums() -> None:
    """S3 and S4 differ only by donor/acceptor swap, so spectral sums should be close."""
    _, _, _, s3 = _load_reference("S3")
    _, _, _, s4 = _load_reference("S4")
    assert abs(s3.sum() - s4.sum()) < 0.1 * max(abs(s3.sum()), abs(s4.sum()))
